const components = [
  "IPL Match Management Service",
  "Status Correction Service",
  "Slang Standardization Service",
  "Filtered Text Removal Service",
  "Slang Management System",
  "IPL Team",
  "Statistical Analysis",
  "Visualized Comments",
  "Classification Service",
  "IPL Team Management Service",
  "User Interface",
  "Data Sets Download Service",
  "Frequency Calculation",
  "IPL Data Sets",
  "Data Sets",
  "Slang Expansion System",
  "Analysis Service",
  "Data Database",
  "Statistical Analysis Service",
  "Status Notification",
  "Data Analyzer",
  "Visualization Service",
  "Slang Standardization Confirmation",
  "Data Processing Service",
  "Slang Text Management Service",
  "User Behavior",
  "Filtered Text",
  "Frequency Data",
  "Status Management Service",
  "Feedback Database",
  "Frequency Calculation Service",
  "Feedback Filter Service",
];

const layers = {
  Server: [
    "IPL Match Management Service",
    "IPL Team",
    "IPL Team Management Service",
    "Data Sets Download Service",
    "Frequency Calculation",
    "IPL Data Sets",
    "Data Sets",
    "Data Database",
    "Data Processing Service",
    "User Behavior",
    "Feedback Database",
    "Frequency Calculation Service",
  ],
  "Server-Side Proxy": [
    "Status Correction Service",
    "Slang Standardization Service",
    "Filtered Text Removal Service",
    "Slang Management System",
    "Statistical Analysis",
    "Classification Service",
    "Slang Expansion System",
    "Analysis Service",
    "Statistical Analysis Service",
    "Data Analyzer",
    "Slang Text Management Service",
    "Filtered Text",
    "Frequency Data",
    "Status Management Service",
    "Feedback Filter Service",
  ],
  broker: ["message broker"],
  "Client-Side Proxy": [
    "Status Notification",
    "Visualization Service",
    "Slang Standardization Confirmation",
  ],
  Client: ["Visualized Comments", "User Interface"],
};

const edges = [
  ["Client", "Client-Side Proxy"],
  ["Client-Side Proxy", "broker"],
  ["broker", "Server-Side Proxy"],
  ["Server-Side Proxy", "Server"],
];

export { components, layers, edges };
